<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:05:25',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:47:59',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 1,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:45:39',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 2,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:45:46',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:47:59',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:47:59',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:47:59',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:47:59',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2022-10-26 16:56:24',
                'updated_at' => '2022-10-26 18:48:04',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Parámetros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-align-left',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2022-10-26 17:33:41',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => 'voyager.categories.index',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2022-10-26 18:39:59',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-refresh',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2022-10-26 19:14:59',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 11,
                'order' => 2,
                'created_at' => '2022-10-27 14:20:59',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => 'voyager.people.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Préstamos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-hand-holding-dollar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-10-28 05:03:27',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => 'loans.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Bóveda',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-vault',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-10-29 01:55:52',
                'updated_at' => '2022-10-29 01:56:08',
                'route' => 'vaults.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Cajeros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cash-register',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-10-29 16:36:14',
                'updated_at' => '2022-10-29 16:36:23',
                'route' => 'cashiers.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Rutas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-route',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 1,
                'created_at' => '2022-11-07 18:28:19',
                'updated_at' => '2022-11-07 19:39:19',
                'route' => 'voyager.routes.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Cobradores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'class="fa-solid fa-motorcycle',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-11-22 01:29:36',
                'updated_at' => '2022-11-22 01:29:45',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}